package com.sinosoft.ddss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ddss.common.entity.FtpData;

public interface FtpDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_data
     *
     * @mbg.generated
     */
    int insert(FtpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_data
     *
     * @mbg.generated
     */
    int insertSelective(FtpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_data
     *
     * @mbg.generated
     */
    FtpData selectByPrimaryKey(Long orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FtpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_ftp_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FtpData record);
    /**
	 * 批量增加子订单
	 * @param list
	 */
	int insertDataList(@Param("list")List<FtpData> list);
	
	/**
	 * 按名称查询ftpdata
	 * @param productName
	 * @return
	 */
	FtpData findByProductName(String productName);
}