package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.OrderFilter;

public interface OrderFilterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_order_filter
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_order_filter
     *
     * @mbg.generated
     */
    int insert(OrderFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_order_filter
     *
     * @mbg.generated
     */
    int insertSelective(OrderFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_order_filter
     *
     * @mbg.generated
     */
    OrderFilter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_order_filter
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderFilter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ddss_order_filter
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderFilter record);
}