package com.sinosoft.ddss.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.sinosoft.ddss.common.entity.ShopInfo;
import com.sinosoft.ddss.common.entity.query.ShopInfoQuery;

public interface ShopInfoMapper {
	/**
	 * 根据购物车id批量删除
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(String ids);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ddss_shop_info
	 *
	 * @mbg.generated
	 */
	int insert(ShopInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ddss_shop_info
	 *
	 * @mbg.generated
	 */
	int insertSelective(ShopInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ddss_shop_info
	 *
	 * @mbg.generated
	 */
	ShopInfo selectByPrimaryKey(Long id);

	/**
	 * 查询购物车内容
	 * 
	 * @return
	 */
	List<ShopInfo> listShopInfo(ShopInfoQuery record);

	/**
	 * 根据用户名查询购物车数据
	 * 
	 * @param record
	 * @return
	 */
	Integer getCountByQuery(ShopInfoQuery record);

	/**
	 * 清空购物车
	 * 
	 * @return
	 */
	int delAllShopCar(String userName);

	/**
	 * 根据id查找购物车信息
	 * 
	 * @return
	 */
	List<ShopInfo> selectByPrimaryKeys(String shopCarIds);

	/**
	 * 批量添加购物车信息
	 * @param shopInfo
	 * @return
	 */
	Integer saveShopInfo(@Param("list")List<ShopInfo> list);

	/**
	 * 删除购物车数据通过dataId
	 * @param record
	 * @return
	 */
	int deleteByDataIds(ShopInfo shopInfo);
	
	/**
	 * 根据dataId查找购物车信息
	 * 
	 * @return
	 */
	List<ShopInfo> selectByDataIds(String dataIds);
}