package com.sinosoft.ddss.dao;

import com.sinosoft.ddss.common.entity.Task;
import java.math.BigDecimal;
import java.util.List;

public interface TaskMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ddss_task
	 *
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Long taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ddss_task
	 *
	 * @mbg.generated
	 */
	int insertSelective(Task record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ddss_task
	 *
	 * @mbg.generated
	 */
	Task selectByPrimaryKey(Long taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ddss_task
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(Task record);

	/**
	 * 根据主单新增任务表记录
	 * 
	 * @param orderMainId
	 */
	void saveTask(Task record);
	
	/**
	 * 批量新增任务表
	 * @param list
	 * @return
	 */
	int saveTaskList(List<Task> list);

}